title = "HyperParameters"

['lidar']
lower_fov = -25.0
upper_fov = 5.0
num = 4
channels = 16.0
x = [0.0, 0.0, 0.0, 0.0]
y = [0.0, 0.0, 0.0, 0.0]
z = [2.4, 2.6, 2.8, 3.0]
roll = [0.0, 0.0, 0.0, 0.0]
pitch = [0.0, 0.0, 0.0, 0.0]