title = "HyperParameters"

# Default: ['lidar'] is the original pyramid placement, ['lidar_roll'] is the pyramid placement with roll angle, ['lidar_pitch'] is the pyramid placement with pitch angle
# the default is to use the original pyramid placement, exchange ['lidar'] and ['lidar_roll'] to use the pyramid placement with roll angle, or exchange ['lidar'] and ['lidar_pitch'] to use the pyramid placement with pitch angle

['lidar']
lower_fov = -25.0
upper_fov = 5.0
num = 4
channels = 16.0
x = [-0.2, 0.4, -0.2, -0.2]
y = [-0.6, 0.0, 0.0, 0.6]
z = [2.2, 2.4, 2.6, 2.2]
roll = [0.0, 0.0, 0.0, 0.0]
pitch = [0.0, 0.0, 0.0, 0.0]


['lidar_roll']
lower_fov = -25.0
upper_fov = 5.0
num = 4
channels = 16.0
x = [-0.2, 0.4, -0.2, -0.2]
y = [-0.6, 0.0, 0.0, 0.6]
z = [2.2, 2.4, 2.6, 2.2]
roll = [-0.28, 0.0, 0.0, 0.28]
pitch = [0.0, 0.0, 0.0, 0.0]

['lidar_pitch']
lower_fov = -25.0
upper_fov = 5.0
num = 4
channels = 16.0
x = [-0.2, 0.4, -0.2, -0.2]
y = [-0.6, 0.0, 0.0, 0.6]
z = [2.2, 2.4, 2.6, 2.2]
roll = [0.0, 0.0, 0.0, 0.0]
pitch = [0.0, -0.09, 0.0, 0.0]