
title = "Parameters"

[pom]
pom_x = 60
pom_y = 40
pom_z = 4

pom_exclude_x_min = 27
pom_exclude_x_max = 33

pom_exclude_y_min = 18
pom_exclude_y_max = 22

pom_exclude_z_min = 0
pom_exclude_z_max = 4

scale = 20

[lidar]
x_min = 29.5
x_max = 30.5
y_min = 19.4
y_max = 20.6
z_min = 2.2
z_max = 3
yaw_min = "known"
yaw_max = "known"
pitch_min = -0.0001
pitch_max = 0.0001
roll_min = -0.0001
roll_max = 0.0001
beam_angle = [-25,-23,-21,-19,-17,-15,-13,-11,-9,-7,-5,-3,-1,1,3,5]
lidar_nos = 4

